name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: holoburda/laravel_app:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies (PHP + Composer)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libzip-dev libpng-dev libonig-dev
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build frontend (npm)
        run: |
          npm install
          npm run build
      - name: Run tests
        run: php artisan test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME .
          docker push $REGISTRY/$IMAGE_NAME
