name: Deploy Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Azure via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH deploy with username & password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          port: 22
          script: |
            cd hackathon-int20h
            sudo git pull origin main
            sudo docker exec hackathon-int20h_app_1 php artisan migrate --force
            sudo docker exec hackathon-int20h_app_1 npm install
            sudo docker exec hackathon-int20h_app_1 npm run build
